In [6]:
#Phần 1
import numpy as np
arr_zeros=np.zeros(5,dtype=int)
arr_zeros[4]=1
print(arr_zeros)

[0 0 0 0 1]


In [3]:
#Phần 2
arr_h=np.arange(10,25)
print(arr_h[::-1])

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [7]:
#Phần 3
arr_k=np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_l=np.array([i for i in arr_k if i!=0])
print(arr_l)

[1 2 8 2 1 3 5]


In [14]:
#Phần 4
arr_4=np.append(arr_l,10)
arr_4=np.append(arr_4,20)
print(arr_4)

[ 1  2  8  2  1  3  5 10 20]


In [17]:
#Phần 5
arr_5=np.insert(arr_4,5,100)
print(arr_5)

[  1   2   8   2   1 100   3   5  10  20]


In [18]:
#Phần 6
arr_6=np.delete(arr_5,[0,1,2])
print(arr_6)

[  2   1 100   3   5  10  20]
