In [1]:
import numpy as np
#Tạo numpy array có giá trị từ 0-9
# arr=[0,1,2,3,4,5,6,7,8,9]
# arr_np=np.array(arr)
# print(arr_np)
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.size

10

In [ ]:
arr_odd=arr[1::2]
arr_even=arr[0::2]
print(arr_odd)
print(arr_even)


In [3]:
arr_odd=arr[arr%2==1]
arr_even=arr[arr%2==0]
print(arr_odd)
print(arr_even)

[1 3 5 7 9]
[0 2 4 6 8]


In [4]:
new_arr=np.where(arr%2==0,arr,100)
print('result:',new_arr)

result: [  0 100   2 100   4 100   6 100   8 100]


In [5]:
arr_update_1=np.array([],dtype=int)
for number in arr:
    if number % 2==0:
        arr_update_1=np.append(arr_update_1,[number])
    else:
        arr_update_1=np.append(arr_update_1,[100])
print(arr_update_1)

[  0 100   2 100   4 100   6 100   8 100]
